name: Pretter

on:
  push:
    branches:
      - feature/add_ci

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Run Prettier
        run: |
          yarn install
          yarn format
      - uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: [ci] apply format